### ISSUE TITLE
如何发布阿里云 上线的呢 咱们可以加一个微信群 一起讨论一下吗 包括一些技术问题的探讨等

### ISSUE THREAD

**Issue by guozimo** [ITCNZ/Nuxt-ssr#10]
如何发布阿里云 上线的呢 咱们可以加一个微信群 一起讨论一下吗 包括一些技术问题的探讨等
如何发布上线呢 
您可以给我

**Comment by guozimo** [comment]
如何发布阿里云 上线的呢 咱们可以加一个微信群 一起讨论一下吗 包括一些技术问题的探讨等
如何发布上线呢
您可以给我
我的微信是gwd1991
qq：915172419

**Comment by ITCNZ** [comment]
可以加QQ群：320243648、722735743
也可以看我的博客文章，有部署教程
