### ISSUE TITLE
如果想后台管理页面的路由是127.0.0.1:3000/admin 改怎样设置呢？

### ISSUE THREAD

**Issue by hlbj105** [ITCNZ/Nuxt-ssr#4]
默认的路由是app.use(nuxt.render)；

显示效果是127.0.0.1:3000

但我想要127.0.0.1:3000/admin

该怎么改？

app.use('/admin',nuxt.render) 使用这样的话会报 _nuxt/下的文件404

这该怎么设置呢？

**Comment by ITCNZ** [comment]
可以查询nuxt官方的路由模块
